project:
  type: website

website:
  title: "Effective LLM Prompting for R"
  navbar:
    right:
      - href: index.qmd
        text: 'Home'

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



